services:
  # Backend API service
  - type: web
    name: voice-bot-api
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENROUTER_API_KEY
        sync: false

  # Frontend static site
  - type: web
    name: voice-bot-client
    env: static
    buildCommand: cd voice-client && npm install && npm run build
    staticPublishPath: ./voice-client/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://voice-bot-api.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html 